version: '3'

services:

  php:
    image: php:7-fpm-alpine
    build:
      context: .
      dockerfile: php.Dockerfile
    volumes:
      - ./bin/archive:/var/www/archive
      - secretbase:/var/www/secretbase
      - ${PWD}/.secretbase.env:/var/www/secretbase/.env

  tagreplacer:
    image: 'cubeghost/tagreplacer:latest'
    ports:
      - 4000:4000
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    volumes:
      - ${PWD}/.tagreplacer.env:/usr/src/app/.env
    depends_on:
      - redis

  secretbase:
    image: 'cubeghost/secretbase:latest'
    tty: true
    volumes: 
      - secretbase:/usr/src/app

  redis:
    image: redis
    ports: 
      - 6379:6739

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./bin/archive:/var/www/archive
      - secretbase:/var/www/secretbase
      - ./static:/var/www/static
      - ${PWD}/nginx/mime.types:/etc/nginx/mime.types
      - ${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/nginx/nginx.development.conf:/etc/nginx/nginx.development.conf
      - certs:/etc/letsencrypt
      - challenge:/var/www/certbot
    command: nginx -c nginx.development.conf
    depends_on:
      - php
      - tagreplacer

volumes:
  secretbase:
  certs:
  challenge: